version: "3.9"

services:
  loader:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      AWS_REGION: "us-west-1"
      RUNNING_ON_EC2: "true"
    volumes:
      - .:/app
    network_mode: "host"
