version: "3.9"
services:
  app:
    build:
      context: ./app
    ports:
      - "8000:8000"
    restart: unless-stopped

  streamlit:
    build:
      context: ./streamlit  
    ports:
      - "8501:8501"
    restart: unless-stopped
