name: Deploy to EC2 from GHCR

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy via SSM
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy Docker image on EC2 via SSM
      run: |
        aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --comment "Deploy Docker container from GHCR" \
          --targets "Key=tag:PROJECT_NAME,Values=${{ secrets.PROJECT_NAME }}" \
          --parameters 'commands=[
            "export GHCR_PAT=$(aws ssm get-parameter --name \"/github/ghcr_pat\" --with-decryption --region '${{ secrets.AWS_REGION }}' --query \"Parameter.Value\" --output text)",
            "echo $GHCR_PAT | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin",
            "docker stop ${{ secrets.CONTAINER_NAME }} || true",
            "docker rm ${{ secrets.CONTAINER_NAME }} || true",
            "docker pull ghcr.io/${{ secrets.GHCR_USERNAME }}/football-analytics:main",
            "docker run -d --name ${{ secrets.CONTAINER_NAME }} \
              --restart unless-stopped \
              --health-cmd=\"curl -f http://localhost:8000/health || exit 1\" \
              --health-interval=30s \
              --health-timeout=10s \
              --health-retries=3 \
              --log-driver awslogs \
              --log-opt awslogs-region=${{ secrets.AWS_REGION }} \
              --log-opt awslogs-group=/docker/football-analytics-dev \
              --log-opt awslogs-stream=football-analytics \
              -p 8000:8000 \
              ghcr.io/${{ secrets.GHCR_USERNAME }}/football-analytics:main"
          ]' \
          --timeout-seconds 600 \
          --region ${{ secrets.AWS_REGION }} \
          --output text
