name: Deploy to EC2 from GHCR

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy via SSM
    runs-on: ubuntu-latest

    steps:
    - name: Assume EC2 SSM IAM role
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1

    - name: Run docker container via SSM
      run: |
        aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --comment "Deploy Docker container from GHCR" \
          --targets "Key=tag:Project,Values=football-analytics-dev" \
          --parameters 'commands=[
            "docker stop football || true",
            "docker rm football || true",
            "docker pull ghcr.io/${{ github.repository }}:latest",
            "docker run -d --name football ghcr.io/${{ github.repository }}:latest"
          ]' \
          --timeout-seconds 600 \
          --region us-west-1 \
          --output text