name: Publish Docker image to GHCR

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # GHCR publish permission

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker tags
      id: vars
      run: |
        VERSION=1.0.0
        ENV_SUFFIX=dev
        echo "IMAGE_TAG=ghcr.io/${{ github.repository }}:${VERSION}-${ENV_SUFFIX}" >> $GITHUB_ENV

    - name: Log in to GHCR
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ env.IMAGE_TAG }} .

    - name: Push Docker image
      run: docker push ${{ env.IMAGE_TAG }}

